import { describe, it, expect } from "vitest";
import { gstime } from "../js/gstime.js";
import { isequalRel } from "./helpers.js";

describe("gstime", () => {
    it("sample date near now", () => {
        const TOLERANCE = 1e-11;
        const epoch_recent = 22669; // approx days since January 0, 1950
        const epoch_jd = 2433281.5; // JD of Jan 0, 1950 (from initl.js)
        const a_date = epoch_recent + epoch_jd;

        expect(Math.abs(gstime(a_date) - 2.14204426986544)).toBeLessThan(TOLERANCE);
        expect(Math.abs(gstime(2455966) - 5.55028019712699)).toBeLessThan(TOLERANCE);
    });

    it("values generated by testmat.m run", () => {
        const TOL = 0.000001;
        expect(isequalRel(gstime(2451723.28495062003), 3.469172342379, TOL)).toBe(true); // 5
        expect(isequalRel(gstime(2453036.41070959019), 1.716027084070, TOL)).toBe(true); // 4632
        expect(isequalRel(gstime(2453912.32412014017), 3.673754967933, TOL)).toBe(true); // 6251
        expect(isequalRel(gstime(2453911.83215444023), 0.574180126903, TOL)).toBe(true); // 8195
        expect(isequalRel(gstime(2453912.06157475011), 2.019617116981, TOL)).toBe(true); // 9880
        expect(isequalRel(gstime(2453519.29417927982), 3.007604046768, TOL)).toBe(true); // 9998
        expect(isequalRel(gstime(2444468.79629787989), 1.265125075736, TOL)).toBe(true); // 11801
        expect(isequalRel(gstime(2453911.52844893001), 4.943902851905, TOL)).toBe(true); // 14128
        // eslint-disable-next-line no-loss-of-precision
        expect(isequalRel(gstime(2453887.17415770982), 2.298863660699, TOL)).toBe(true); // 16925
        expect(isequalRel(gstime(2453734.29166666977), 0.407188563806, TOL)).toBe(true); // 20413
        expect(isequalRel(gstime(2453911.52341243997), 4.912171010008, TOL)).toBe(true); // 21897
        expect(isequalRel(gstime(2453829.96235912014), 6.267076519855, TOL)).toBe(true); // 22312
        expect(isequalRel(gstime(2453912.05909107020), 2.003968969617, TOL)).toBe(true); // 22674
        expect(isequalRel(gstime(2453910.95752051985), 1.346832291139, TOL)).toBe(true); // 23177
        expect(isequalRel(gstime(2449657.99999999022), 3.849219568564, TOL)).toBe(true); // 23333
        expect(isequalRel(gstime(2453907.26535463007), 3.217495488339, TOL)).toBe(true); // 23599
        expect(isequalRel(gstime(2453912.54061739985), 5.037771726289, TOL)).toBe(true); // 24208
        expect(isequalRel(gstime(2453044.18057285016), 0.403698640659, TOL)).toBe(true); // 25954
        expect(isequalRel(gstime(2453842.24503247021), 1.971276525301, TOL)).toBe(true); // 26900
        expect(isequalRel(gstime(2453910.35818871018), 3.853994597295, TOL)).toBe(true); // 26975
        expect(isequalRel(gstime(2453913.28615832981), 3.451783621544, TOL)).toBe(true); // 28057
        expect(isequalRel(gstime(2453911.07071135985), 2.059978512381, TOL)).toBe(true); // 28129
        expect(isequalRel(gstime(2453902.71788665978), 5.982608943601, TOL)).toBe(true); // 28350
        expect(isequalRel(gstime(2453913.31079183985), 3.606984295022, TOL)).toBe(true); // 28623
        expect(isequalRel(gstime(2453911.96683397004), 1.422713433736, TOL)).toBe(true); // 28626
        expect(isequalRel(gstime(2453703.52012661006), 1.313288306073, TOL)).toBe(true); // 28872
        expect(isequalRel(gstime(2453905.76783845015), 0.065747677456, TOL)).toBe(true); // 29141
        expect(isequalRel(gstime(2453912.78732009977), 0.308909173693, TOL)).toBe(true); // 29238
        expect(isequalRel(gstime(2444514.48708464997), 0.108290141670, TOL)).toBe(true); // 88888
    });
});
